[package]
name = "daft"
edition = "2021"

[dependencies]
aws-config = "1.5.8"
aws-sdk-sts = "1.46.0"
serde_yaml = "0.9.34"
tempdir = "0.3.7"
toml = "0.8.19"
which = "6.0.3"
map-macro = { version = "0.3.0", features = ["hashbrown"] }
anyhow = { version = "1.0.89", features = ["backtrace"] }
tokio = { version = "1.40.0", features = ["full"] }
hashbrown = { version = "0.15.0", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rstest = "0.23.0"
