[package]
name = "daft_launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
toml = "0.8.19"

[dependencies.clap]
version = "4.5"
features = ["derive"]

[dependencies.semver]
version = "1.0"
features = ["serde"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
