# This is a template configuration file for daft-launcher with Kubernetes provider
[setup]
name = "my-daft-cluster"
requires = "<requires>"
python_version = "<python-version>"
ray_version = "<ray-version>"

[setup.k8s]
namespace = "default" # Optional, defaults to "default"

# Job definitions
[[job]]
name = "example-job"
command = "python my_script.py"
working-dir = "~/my_project"
