# This is a template configuration file for daft-cli with Kubernetes provider

[setup]
name = "my-daft-cluster"
requires = "<requires>"
python-version = "<python-version>"
ray-version = "<ray-version>"

[setup.byoc]
namespace = "default" # Optional, defaults to "default"

# Job definitions
[[job]]
name = "example-job"
command = "python my_script.py"
working-dir = "~/my_project"
