# This is a default configuration file that you can use to spin up a ray-cluster using `daft-launcher`.
# Change up some of the configurations in here, and then run `daft up`.
#
# For more information on the availale commands and configuration options, visit [here](https://eventual-inc.github.io/daft-launcher).
#
# Happy daft-ing!

[setup]
name = "daft-launcher-example"
version = "<VERSION>"
provider = "aws"
region = "us-west-2"

# This is the user profile that ssh's into the head machine.
# This value depends upon the AMI that you choose.
# For AWS AMIs, keep it as 'ec2-user'; for Ubuntu AMIs, change it to 'ubuntu'.
# ssh-user = "ec2-user"

# Fill this out with your custom `.pem` key, or generate a new one by running `ssh-keygen -t rsa -b 2048 -m PEM -f my-key.pem`.
# ssh-private-key = "~/.ssh/ronnie-keypair.pem"
