# This is a template configuration file for daft-launcher with a BYOC provider

[setup]
name = "my-daft-cluster"
version = "<VERSION>"

[setup.byoc]
namespace = "default" # Optional, defaults to "default"

# Job definitions
[[job]]
name = "example-job"
command = "python my_script.py"
working-dir = "~/my_project"
