# This is a default configuration file that you can use to spin up a ray-cluster using `daft-launcher`.
# Change up some of the configurations in here, and then run `daft up`.
#
# For more information on the availale commands and configuration options, visit [here](https://eventual-inc.github.io/daft-launcher).
#
# Happy daft-ing!

[setup]
name = "daft-launcher-example"
requires = "<REQUIRES>"
region = "us-west-2"
number-of-workers = 4

# The following configurations specify the type of servers in your cluster.
# The machine type below is what we usually use at Eventual, and the image id is Ubuntu based.
# If you want a smaller or bigger cluster, change the below two configurations accordingly.
instance-type = "i3.2xlarge"
image-id = "ami-04dd23e62ed049936"

# This is the user profile that ssh's into the head machine.
# This value depends upon the `image-id` value up above.
# For Ubuntu AMIs, keep it as 'ubuntu'; for AWS AMIs, change it to 'ec2-user'.
ssh-user = "ubuntu"

# Fill this out with your custom `.pem` key, or generate a new one by running `ssh-keygen -t rsa -b 2048 -m PEM -f my-key.pem`.
# Make sure the public key is uploaded to AWS.
ssh-private-key = "~/.ssh/my-keypair.pem"

# Fill in your python dependencies here.
# They'll be downloaded using `uv`.
dependencies = []
