name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv python install
      - name: Install build dependencies
        run: |
          uv v
          source .venv/bin/activate
          uv pip install twine
      - name: Build the package
        run: |
          source .venv/bin/activate
          uv build
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: "${{ secrets.PYPI_API_TOKEN }}"
        run: |
          source .venv/bin/activate
          twine upload dist/* --skip-existing
